//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laboratornaya1
{
    using System;
    using System.Collections.Generic;
    
    public partial class call
    {
        public int ID_Call { get; set; }
        public Nullable<System.DateTime> Time_of_start { get; set; }
        public int Amount { get; set; }
        public Nullable<int> Price { get; set; }
        public int ID_User_FK_ { get; set; }
        public int ID_Type_of_Call_FK_ { get; set; }
    }
}
