//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laboratornaya1
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_of_call
    {
        public int ID_Type_of_Call { get; set; }
        public string Name { get; set; }
    }
}
